### ISSUE TITLE
t test and examples issues

### ISSUE THREAD

**Issue by PhilterPaper** [sciurius/perl-SVGPDF#1]
Thanks for getting this out on GitHub, and for fixing File::LoadLines (installs OK on Windows now). I look forward to seeing this package on CPAN! Do you have anything holding it up, or do you wish to do more work on it? I'm not immediately ready to make use of it in PDF::Builder, but I'm hoping to get to it within a few months, with release 3.027 perhaps by early to mid Spring.

So far I've only run with the default PDF::API2. I'll let you know if any problems turn up with PDF::Builder.

Running Makefile.PL, I get
```
C:\Users\Phil\Desktop\jv-SVGPDF>Makefile.PL
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        examples/fontconfig.pl
Please inform the author.
```
before I installed Image::Info, but it went away after installing that package. Make (in Windows with Strawberry Perl, 'gmake') test seems to run OK, as does make install, 

Trying to run the t-tests in a batch file (script), all goes well except for t/900_regtest.pl (note that this is a Perl program and not a standard t-test):
```
C:\Users\Phil\Desktop\jv-SVGPDF>perl t\900_regtest.pl
Use of uninitialized value $module in concatenation (.) or string at C:/Strawberry/perl/site/lib/Test/More.pm line 1022.
Use of uninitialized value $module in concatenation (.) or string at C:/Strawberry/perl/site/lib/Test/More.pm line 1032.
not ok 1 - use ;
#   Failed test 'use ;'
#   at t\900_regtest.pl line 15.
Use of uninitialized value $module in concatenation (.) or string at C:/Strawberry/perl/site/lib/Test/More.pm line 1038.
#     Tried to use ''.
#     Error:  syntax error at t\900_regtest.pl line 15, near "#line 15 t\900_regtest.pl
# use  @"
ok 2 - use SVGPDF;
Can't return outside a subroutine at t\900_regtest.pl line 21.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 2.
```
Is $api supposed to be set externally somewhere? Is there supposed to be _both_ a .pl _and_ a .t for 900_regtest?

Turning to running the examples/ from a batch script, it works OK once I run mathjax.pl from within examples/ (mathjax.svg is hard coded to require that).

I have no objection to your providing any or all of the SVG samples (as examples) I gave you earlier. Do you think there might be copyright restrictions on any of them?

**Comment by sciurius** [comment]
Ah, the wrinkles...

> Warning: the following files are missing in your kit:        examples/fontconfig.pl

Good catch. I've added this file to git.

> all goes well except for t/900_regtest.pl

You're not supposed to run this as an individual perl program. It is included from t/900_regtest.t and t/901_regtest.t.

`gmake test` should take care of running the tests.

**Comment by PhilterPaper** [comment]
I did run `gmake test` and `gmake install` and they were OK. I just like to make a batch script to run t-tests and examples _outside_ of the build/install process, to see if everything is OK when I make a change. See PDF::Builder tools/2_t-tests.pl, etc.

I _did_ get around to changing the t-tests and examples to use PDF::Builder 3.026, and they ran fine. I guess the decks are clear to start working on SVG image support on the PDF::Builder side.

Feel free to close this ticket whenever...

**Comment by sciurius** [comment]
Thanks!
