### ISSUE TITLE
Problems with some samples

### ISSUE THREAD

**Issue by PhilterPaper** [sciurius/perl-SVGPDF#2]
I threw the 11 sample SVG files I sent you earlier, against your sample code (attached below). 

1. The following worked with no apparent problem: attrPriority
2. GPhidden1, GPpm3dsurface, and GPscatter5 appear to be OK, except they gained a box (in the last stroke color) around them
3. The following almost worked well: QRcode (a bit on the heavy side) and ATS_flow (vertical dashed line has a thin solid line down it)
4. 'go' mascot, which appears to embed a PNG image as data, gives an error `Error doing init_io: unopened file handle? at C:/Strawberry/perl/site/lib/PDF/Builder/Resource/XObject/Image/PNG_IPL.pm line 151.` Are you passing something other than a file name or handle to image_png()?
5. 'MJdisplay' is pretty good, except that it's "centered" way too far to the right. It also outputs some debug prints
6. 'MJdisplayNoTag' is blank (possibly way out of scale)
7. 'MJinline' is way off scale, showing only the "1" (taking up the whole page)
8. 'UPC_A' the bars are way too thick and merge together in clumps

[samples.pl.txt](https://github.com/sciurius/perl-SVGPDF/files/13709035/samples.pl.txt)
[samples.pdf](https://github.com/sciurius/perl-SVGPDF/files/13709071/samples.pdf)

Just giving you a "heads up" early so you have time to take a look at these issues. Please also test against the SVG samples I provided, and not just your own applications' samples.

ATS_flow is a little too wide... do you have a recommended way to scale the object? Do you still need the calling program to provide that font information callbck that you needed earlier? And will there be a documented way to feed either a file path or a data stream containing the SVG? Your sample.pl seemed to suggest "yes".

EDIT: Make numbered list so we can address the individual points.

**Comment by PhilterPaper** [comment]
By the way, as I said some months ago, for MathJax "display" mode I _can_ either strip out the tag and the auto-centering from the SVG, or just create it as normal text (without tag) and in my code center the image and add a tag. So, don't knock yourself out trying to get the "display" auto-centering and tag to work -- I can work around it.

'Tis the season, and all that -- Merry Christmas and a Happy New Year! Or, Season's Greetings, if that's more your thing.

**Comment by PhilterPaper** [comment]
A thought on the QR code and UPC bar code looking too heavy: perhaps you are stroking the outlines of the filled areas, when they shouldn't be? Especially if the stroke is quite heavy itself! I seem to recall that we went through a discussion about this six months or so ago, regarding the MathJax output.

**Comment by sciurius** [comment]
Yes, there is a combination of styles and attributes that sometimes? lead to a stroke width while there should be no stroking at all. I made a tweak for MathJax to avoid this, maybe I should allow a user setting to control this. Temporarily, until I can nail it down.

I'll have a look at the other remarks one of these days.
I have currently no plans to dive into the svg-in-svg (MathJax display) again.

**Comment by sciurius** [comment]
I have released 0.081.
1. Ok.
2. Fixed.
3. a. QR: What do you mean with 'a bit heavy'? The blacks and whites are [exact to the pixel](https://github.com/sciurius/perl-SVGPDF/assets/1118804/8f1f5a77-32cd-425b-aa44-71d711cad93f).
b. I can't see any thin lines next to the vertical dashed line. Can you make a magnified screen dump to show the thin line?
4. [No problems here](https://github.com/sciurius/perl-SVGPDF/assets/1118804/62be101a-66e5-4e68-8bd3-4229a86abe9b).
5. One of the messages is "SVG: preserveAspectRatio - not fully implemented, expect strange results."
6. The images are rendered to the given size of the viewbox, which is 43414.9 px wide... It needs scaling. You can use the `width` and `height` attributes to determine the scaling.
7. Same.
8. I think that is a display problem. When [magnified](https://github.com/sciurius/perl-SVGPDF/assets/1118804/11e6846f-85b2-4d2c-8b0b-a21721016fa1) you can see that the anti-aliasing makes the lines blurry. When printed at 300 or 600dpi the bar codelines should be crisp.

**Comment by sciurius** [comment]
If you want correct fonts you must supply a fontmanager callback to have SVGPDF use the same fonts (i.e., the result from calling $pdf->font()) as used in the rest of the PDF. This also prevents all images from using a different instance of the same font, making the PDF document big.

SVGPDF takes its input using the [loadlines](https://metacpan.org/pod/File::LoadLines#loadlines) method of the File::LoadLines module. So it can handle constant data, an opened file handle, and the name of a file (on disk or on the network).

**Comment by sciurius** [comment]
I tried a barcode generated by https://barcode.tec-it.com/en/UPCA and it comes out very crisp, even on the display.

**Comment by PhilterPaper** [comment]
OK, let me install the new version, and try updating my code to use the width and height settings, and see what changes. I'll get back to you later with screenshots and results. Thanks!

**Comment by PhilterPaper** [comment]
1. (attrPriority) OK
2. (GP*) OK now (thanks)
3. a) QRcode top is 
![QRbrw](https://github.com/sciurius/perl-SVGPDF/assets/13512500/5b55e361-1f18-4756-b030-17e2d8efbda9) Firefox browser of .svg, bottom is
![QRpdf](https://github.com/sciurius/perl-SVGPDF/assets/13512500/189da12f-119f-433e-b9f9-2880b1b92bd3) PDF via Adobe Acrobat Reader. I'm not sure now whether the browser copy is too light or the PDF is too heavy.
b) ATS_flow top is
![ATbrw](https://github.com/sciurius/perl-SVGPDF/assets/13512500/2fc094df-4b29-4723-b6c2-a9e1daace5b1) Firefox browser of .svg with clean dashed line, bottom is 
![ATpdf](https://github.com/sciurius/perl-SVGPDF/assets/13512500/4eb89425-fd3c-4b94-836c-ab593c9441f2) PDF via Adobe Acrobat Reader. Note the thin line through the vertical dashed line.
4. (Go) It works for me if I disable the faster Image::PNG::Libpng mode and use pure Perl. It works for me using PDF::API2, so this may indicate a problem with my image_png() code when it uses Image::PNG::Libpng (API2 supposedly is using that library too). Anyway, probably nothing you need to do on this one. Do you happen to have Image::PNG::Libpng installed?
5. The messages I get for MJdisplay are
```
C:\Users\Phil\Desktop\SVGPDF>samples.pl
processing input SVG 'SVG_samples/MJdisplay.svg'
disp dx=300.046772257419, dy=0
disp dx=-13.3663821273758, dy=0
processing input SVG 'SVG_samples/MJdisplayNoTag.svg'
processing input SVG 'SVG_samples/MJinline.svg'
```
Also, something in MJdisplay may be leaving the processor in a strange state... none of the following samples appear!
6. I briefly tried the `width` and `height` attributes, but they produced undefined values. Are they expected to be undefined on the other samples? I guess I can try checking if those attributes are defined, if they may not always be. I haven't tried them with only the MJ* samples.
7. Same
8. (UPC_A) This may be the same problem I encountered with merged bars in the Builder Barcode sample page. If I magnify it to more than 150% scaling, the bars are distinct. I'm running on a low-end HP laptop with Windows and the free Adobe Acrobat Reader, so that combination may just produce poor results (although the tec-it.com BC example look nice and crisp).

All images given above are supposedly scaled 100%, but you can see that they ended up somewhat different sizes.

**Comment by sciurius** [comment]
Rendering SVG to PDF is a discrete process. A 100x100 rectangle in SVG yields a 100x100 rectangle in PDF. A 1-pt line yields a 1-pt line. How the end result _looks_, the 'crispyness', depends on the imager hardware (the laptop monitor, the print engine). A little zooming already makes a big difference.

Apparently, free Adobe Acrobat on a low-end HP laptop with Windows is not a very good imager (also considering the ghost lines in the ATF flow example).

The difference in image sizes is likely 75%. SVG images are rendered in points (1/72 inch) while imagers work with pixels. Browsers typically render at 96dpi, maybe Acrobat uses 72dpi? The svgpdf program has a `--dpi` command line option to try.

I can reproduce the error when using `Image::PNG::Libpng`. In case of the `go.svg` sample, in `SVGPDF::Image` I pass an `IO::String` object to `$pdf->image`. This should be a perl filehandle but maybe `libpng` has a different opinion?

**Comment by PhilterPaper** [comment]
OK, I've made some progress on this. I finally got the hang of scaling the images and correctly positioning them (the "object()" doc was wrong). The only major issue is seeing what is going wrong with the "go" PNG image when using Image::PNG::Libpng. I think it's working OK in PDF::API2 (which supposedly uses that library), so it must be a bug in my code. I'll keep working at it.

There are still some minor glitches (the line through the dashed line in ATS_flow, the clumping of the UPC_A barcode), but otherwise, it seems to be working pretty well. You say that those artifacts are likely a result of low-end hardware... if they display OK for you on higher-end gear, I'll just have to live with it. What I have is likely similar to what a _lot_ of people trying to read PDFs are going to be using, so I'd be happier if they displayed a little better, but what can be done? It may also be the Reader (Adobe Acrobat Reader, free version), but unfortunately that one is extremely common. The QRcode still seems a bit "heavy", but I'm not sure exactly _what_ it's supposed to look like. If it looks OK to you on a better machine, and a phone can process it, I'll just have to live with it.

Should I put any more effort into MJdisplay.svg? If I hear you correctly, you're not planning to support this dynamic placement (nested `<svg>'s`). As I said, I can work around it (as with MJdisplayNoTag.svg) and center it and add a tag in my code.

[samples.pl.txt](https://github.com/sciurius/perl-SVGPDF/files/13760408/samples.pl.txt)
[samples.pdf](https://github.com/sciurius/perl-SVGPDF/files/13760409/samples.pdf)

I may or may not get to do anything on this over the next few days (holidays and all that), but will try to get back to the PNG issue fairly soon. Thanks for your work on this, and I wish you and yours a wonderful holiday!

**Comment by sciurius** [comment]
PDF::API2 does not use Image::PNG::Libpng. 

I installed Acrobat Reader and it does, indeed, show peculiar behaviour.
In the [QR Code](https://github.com/sciurius/perl-SVGPDF/assets/1118804/3f0950f9-b7c3-4cac-b542-5b50146d130b) you can clearly see that the proportion of the blacks and whites is not 1:1. For example in the big square top left the black border should be of equal width as the white border. When you zoom in (in Acrobat) the proportions get better, indicating that the image is okay. In my case, Acrobat uses a screen resolution of 110dpi (no idea where that comes from). When I change the screen resolution to system setting (96dpi) the QR looks much nicer. Anyway, in either setting I have no problems scanning the QR at this size. And in print it looks crispy sharp.

> What I have is likely similar to what a lot of people trying to read PDFs are going to be using

I doubt this. Out of the box there is excellent support for showing and printing PDF documents in the browser. Only when you use Acrobat Reader you see strange things. But why would you install Acrobat Reader in the first place? So I think most users will use the system default viewer, which behaves correcty.

If the way Acrobat Reader shows the PDF bothers you, and other viewers do it okay, I think you should take this up with Adobe.

> If I hear you correctly, you're not planning to support this dynamic placement (nested <svg>'s).

Yes, I currently have no plans to improve this. It is great that you can work around this.

Wishing you all the best for the holidays and the new year!

**Comment by PhilterPaper** [comment]
> PDF::API2 does not use Image::PNG::Libpng

Actually, it _does_ (or at least, _tries_ to). Look in API2/Resource/XObject/Image/PNG.pm. Under processing for RGB+Alpha, you will see a call to `unprocess()`, with the 8th parameter `$file`. It does enter `sub process`, `require Image::PNG::Libping;` (I do have it installed), and further down, `eval` `Image::PNG::Libping->read_png_file($file)`. The `$libpng` result is empty, though, so I would say that it failed to work. Using `eval`, that is apparently suppressing any error messages. If I comment out `eval {` and `}`, I see

> Cannot open 'IO::String=GLOB(0x49454b0)' for reading: Invalid argument at C:/Strawberry/perl/site/lib/PDF/API2/Resource/XObject/Image/PNG.pm line 314.

At this point, instead of returning a string of the PNG contents, it falls through to try the XS version. I don't have that installed, so it falls through again to use the slow pure Perl code at the bottom. I suspect that you will find the same thing happening, assuming that you have IPL installed.

Regarding PDF::Builder, if you tell it to _not_ use IPL (via `'nouseIPL=>1` in the image() call) it will work fine. In SVGPDF/Image.pm line 49, change
```
	# Make the image. Silence missing Image::PNG::Libpng warnings.
	$img = $self->root->pdf->image( IO::String->new($data),
					silent => 1 );
    }
    elsif ( $link =~ m!^.+\.(png|jpe?g)$! && -s $link ) {
	# Make the image. Silence missing Image::PNG::Libpng warnings.
	$img = $self->root->pdf->image($link, silent => 1 );
    }
    else {
```
to
```
	# Make the image. Silence missing Image::PNG::Libpng warnings.
	$img = $self->root->pdf->image( IO::String->new($data),
					silent => 1, nouseIPL => 1 );
    }
    elsif ( $link =~ m!^.+\.(png|jpe?g)$! && -s $link ) {
	# Make the image. Silence missing Image::PNG::Libpng warnings.
	$img = $self->root->pdf->image($link, silent => 1, nouseIPL => 1 );
    }
    else {
```
API2 ignores 'nouseIPL', and Builder uses it to use the non-IPL version of the code.

This is at least a workaround -- it's not the best thing, particularly if someone wants to make use of PNG features found in IPL and not the pure Perl library (you may want to put in a note in the POD). Better would be to find out _why_ IPL doesn't seem to like the "filehandle" you are providing for it via IO::String. If that's not a quick and easy fix, this workaround will do: API2 fails anyway, and falls through to slower code, and Builder won't try to use IPL at all.

What are your thoughts?

> But why would you install Acrobat Reader in the first place?

Most computer users in the world are (unfortunately) on Windows, and any web site offering a PDF to download/view also gives a link to Adobe to download a free copy of Adobe Acrobat Reader. That's why I call it the closest thing there is to a "reference" installation, even though it seems to have plenty of shortcomings. If a PDF displays even half way decently on AAR, it ought to be fine on a better Reader. It's unfortunate that AAR has a number of glitches, but that's what we have to live with.

**Comment by sciurius** [comment]
I see. PDF::Builder has a PNG_Lib module which API2 has not, so I assumed API2 did not use libpng.

I stil do not agree on the AAR issue. What you describe is the situation 15 years ago, when PDF was getting up speed and AAR the (only) tool to use. But now Windows has built-in support for PDF. Most web pages have something like "Click here to view this document and if you cannot open it click here to install a free PDF reader". But the document already opens so noone installs that free reader.

**Comment by PhilterPaper** [comment]
Well yes, it's true that almost any PDF Reader _other_ than AAR will do a better job than AAR. Unfortunately, AAR still has a tremendous mind-share among PDF users (especially on Windows, where "Adobe" is almost a generic term for a Reader), so it would be nice to have our products produce good results using it, but we may just have to settle for what we can get with AAR, and advise users to try something better.

I did try samples.pdf on Firefox, Chrome, and Edge built-in PDF Readers (as well as several other standalone Readers), and the results were quite good (none showed the solid line through the dashed line in ATS_flow, and most did a better job with UPC_A). Enclosed is the latest/last sample list:
[samples.pl.txt](https://github.com/sciurius/perl-SVGPDF/files/13762628/samples.pl.txt)
[samples.pdf](https://github.com/sciurius/perl-SVGPDF/files/13762629/samples.pdf)

built using PDF::Builder. Note that "go" is correct because I put in the `nouseIPL=> 1` in your Image.pm, as detailed previously. I also added a switch to show the viewBox (which goes off the right side in a couple of cases) and any baseline (MJ examples).

Regarding MJdisplay, I'm OK with not trying to support nested `<svg>s` (tag and centered). I expect to be able to work around it. If you should change your mind and find a fix for it (and support it), please let me know. It is disabled in samples.pl.

One very minor nit to think about (it may not be worth doing anything about it). The pm3D colored surface plot, in a browser (direct SVG render) is opaque and hides the axes. The PDF output is slightly translucent (in any Reader), permitting the axes to show through the surface a bit -- I don't know if you're doing something with transparency, or there are gaps in the rendered surface, letting bits of background show through, but there _is_ a slight difference between browser and PDF.

Please confirm when you will be adding the `nouseIPL` flag (or have fixed it so IPL accepts the "opened filehandle"). With that, it looks like SVGPDF will be suitable for PDF::Builder (and PDF::API2) work, whenever you decide to release it on CPAN. Of course, you may still have further development to go for your applications, but at this time it appears to do everything I need. I'll let you get back now to your previously scheduled Holiday Events! :-)

**Comment by PhilterPaper** [comment]
`ref($file) eq "IO::String"`, I believe would work to detect this case. Would `read_from_scalar()` be used instead of `init_io()` and possibly other calls? I'll have to look around for this, and see how major a change it is to the code. I'm concerned that it could end up a major re-architecture of PNG code (it might even be better to just use the API2 version of the code!). If a modification to PNG_IPL.pm is what it takes to work properly. If you want to hold off for a bit on putting in `nouseIPL => 1` until I've looked into it, that's OK. Regarding API2, it will still fail to use IPL, but at least will work more or less (pure Perl code).

Can I assume that you've looked at IO::String and File::LoadLines to see if you're possibly creating an "open filehandle" incorrectly? The ideal situation would be to create it such that it works properly with both the existing API2 and Builder code.

**Comment by sciurius** [comment]
> Can I assume that you've looked at IO::String and File::LoadLines to see if you're possibly creating an "open filehandle" incorrectly? 

Considering what Ben says in https://github.com/benkasminbullock/image-png-libpng/issues/39#issuecomment-1868711465 it seems that IO::String is a good filehandle als long as it is in Perl world. Crossing the C boundary is apparently not working. Also, IO::String looks unmaintained.

> By the way, can you do any testing to see if the same problem arises with GIF, JPEG, etc. embedded images? ... I don't have any other such SVG files to test with,

It is totally unrelated to SVG. See the 3-line samples I posted to https://github.com/benkasminbullock/image-png-libpng/issues/39.

````
use File::LoadLines qw(loadblob);
use IO::String;
my $fh = IO::String->new(loadblob($imagename));
...
````

**Comment by sciurius** [comment]
One of the reasons I wrote File::LoadLines is to have a consistent means to deal with input sources. 
* scalar : file name on disk or network
* ref scalar : file data
* ref GLOB : file handle

I see that PDF::Builder image methods do not distinguish the latter refs. They do, however, check for ref GD::Image.

One of the reasons IO::String is practically obsolete is that using a scalar ref is much easier and well-supported.

**Comment by PhilterPaper** [comment]
I don't think I've ever tried any of the image routines with open Perl filehandles rather than plain filenames. I did go ahead and look at the documentation for all the image_* calls, and all claim to accept either a filename or an open filehandle. The exception is Graphics::TIFF (using libtiff), which does not accept a filehandle, perhaps for the very reason we're seeing problems with in PNG. I believe that only PNG (with IPL) and TIFF (with GT) are trying to use C code XS libraries, and cannot accept Perl filehandles (?). I will go ahead and try the `read_from_scalar()` call, and see where I get with that. If it works, I will suggest to the Graphics::TIFF author that kind of code might be possible with GT.

It would be a shame if XS libraries cannot accept open Perl filehandles. The Perl wrappers around the libraries might be modified to use IO::String-packaged content. The only alternative I can think of at this moment is to write out the file content into a temporary file, and pass the path/name to the XS routine. It's kind of clumsy, but might work?

**Comment by PhilterPaper** [comment]
I'm not having much luck using `read_from_scalar()` in PNG_IPL.pm... perhaps you are more familiar with IO::String usage? Instead of calling `$png->init_io($fh)` (which blows up for an IO::String), I check if `ref($fh) eq 'IO::String'`, and if so, run `$png = read_from_scalar($fh);`. `$fh` is (prints as) `IO::String=GLOB(0x4885ea0))` and it gives an error:
> libpng error: Not a PNG file

So, I "attach" the content of the IO::String to an existing string: `my $string = ''; $fh->open($string); $png = read_from_scalar($string);` and now the error is
> Request for too many bytes 8 on a scalar of length 0 at read position 0.

(`$string` is apparently still ''). Is there a way to dereference $fh so that it's a string with the base64 encoding undone and what I presume is a proper PNG content that read_from_scalar is looking for?

I'm also concerned that if I try reading in the PNG content this way, it will miss the `$xform` settings for transparency and handling 16bps samples (`read_png($xform)`).

-------------------------------------------------------------
I see that SVGPDF has just shown up on CPAN. Thanks! You might want to remember to update Changes with each release (it's a couple back right now).

**Comment by sciurius** [comment]
If I drop the IO::String in favour of a scalar reference, just few changes are required. The [attached zip](https://github.com/sciurius/perl-SVGPDF/files/13767335/bb.zip) contains the modified PDF/Builder.pm and lib/PDF/Builder/Resource/XObject/Image/PNG_IPL.pm with demo program.

**Comment by PhilterPaper** [comment]
Oka-a-a-ay, I've got something working, at least for this example. I just read the Perl IO::String "filehandle" into a local string, and fed that to read_from_scalar(). I'm not sure if I'm getting the various optional transforms done in this mode.

In PNG_IPL.pm, change
```
    my $fh = IO::File->new();
    my $png = create_read_struct();
    if (ref($file)) {
        $fh = $file;
    } else {
        open $fh, '<', $file or die "$!: $file";
    }
    binmode($fh, ':raw');
    $png->init_io($fh);

    my ($w,$h, $bpc, $cs, $im, $palette, $trns);
    $self->{' stream'} = '';
    $self->{' nofilt'} = 1;

    # slurp whole PNG file into $png structure
    my $xform = PNG_TRANSFORM_IDENTITY;  # default bit flag (0)
    my $transparency = 1; # default YES, allow transparency/Alpha
    if ($opts{'notrans'}) { 
        $transparency = 0;
	$xform |= PNG_TRANSFORM_STRIP_ALPHA; 
	# this appears to turn cs=4 into cs=0, and cs=6 into cs=2
    }
    if ($opts{'force8bps'}) {
	$xform |= PNG_TRANSFORM_STRIP_16;
	# this reduces 16bps channels to 8bps
    }
    $png->read_png($xform);
    close($fh);

    # what chunks are available?
```
to
```
    my $fh = IO::File->new();
    my $png = create_read_struct(); 
    if (ref($file)) {
        $fh = $file;
    } else {
        open $fh, '<', $file or die "$!: $file";
    }
    binmode($fh, ':raw');

    my ($w,$h, $bpc, $cs, $im, $palette, $trns);
    $self->{' stream'} = '';
    $self->{' nofilt'} = 1;

    # slurp whole PNG file into $png structure
    my $xform = PNG_TRANSFORM_IDENTITY;  # default bit flag (0)
    my $transparency = 1; # default YES, allow transparency/Alpha
    if ($opts{'notrans'}) { 
        $transparency = 0;
	$xform |= PNG_TRANSFORM_STRIP_ALPHA; 
	# this appears to turn cs=4 into cs=0, and cs=6 into cs=2
    }
    if ($opts{'force8bps'}) {
	$xform |= PNG_TRANSFORM_STRIP_16;
	# this reduces 16bps channels to 8bps
    }

    # IO::String form "filehandle" from SVG doesn't play well with IPL
    # (wants C FILE *fh)
    if (ref($fh) eq 'IO::String') {
	# ref to GLOB (IO::String creation)
	local $/;
	my $string = <$fh>; # slurp in the whole thing
	$png = read_from_scalar($string);
	$png->set_transforms($xform);
    } elsif (ref($fh)) {
	# scalar ref with actual data?
	$png = read_from_scalar($fh);
	$png->set_transforms($xform);
    } else {
	# a filename
        $png->init_io($fh);  
        $png->read_png($xform);
    }
    close($fh);

    # what chunks are available?
```

What do you think? Does it look clean to you? Am I doing your third case correctly (and do we have test data for it)?

**Comment by sciurius** [comment]
You're certainly on the right track.

In the case of ref($file) eq 'IO::String', you can use `${$file->string_ref}` to get the content data.
I would suggest to explicitly test for the ref($file) eq `SCALAR`.
````
    if (ref($fh) eq 'IO::String') {
	# ref to GLOB (IO::String creation)
	$png = read_from_scalar(${$fh->string_ref});
	$png->set_transforms($xform);
    } elsif (ref($fh) eq 'IO::File' || ref($fh) eq 'GLOB') {
	...unmodified...
    } elsif( ref($file) eq 'SCALAR' ) {
	# scalar ref with actual data
	$png = read_from_scalar($$fh);
	$png->set_transforms($xform);
    } else {
        die("Unhandled input");
    }
````
Test case attached.
[images.zip](https://github.com/sciurius/perl-SVGPDF/files/13771067/images.zip)

**Comment by PhilterPaper** [comment]
Your latest changes to PNG_IPL.pm appear to work OK in all my tests (t/png.t, go.svg, my suite of PNG tests) on Perl 5.26, 5.32, and 5.38. Then I tried your "nice.pl" (on 5.38). It fails on test 4:
```
Case 1: File
Case 2: File handle
Case 3: IO::String
Case 4: Scalar
Can't call method "seek" on unblessed reference at C:/Strawberry/perl/site/lib/PDF/Builder.pm line 4226.
```
It may have something to do with `loadblob()` (I don't recall seeing that before). Does this work for you in API2? It does NOT for me. It appears that something similar to the changes for PNG_IPL.pm need to be done in Builder.pm `image()`. The code in question is
```
    if      (ref($file) eq 'GD::Image') {
        return $self->image_gd($file, %opts);
    } elsif (ref($file)) {
        $format ||= _detect_image_format($file);
	# JPEG, PNG, GIF, and P*M files can be detected
	# TIFF files cannot currently be detected
	# GD images are created on-the-fly and don't have files
    }
```
and
```
sub _detect_image_format {
    my $fh = shift();
    $fh->seek(0, 0);
    binmode $fh, ':raw';

    my $test;
    my $bytes_read = $fh->read($test, 8);
    $fh->seek(0, 0);
    return unless $bytes_read and $bytes_read == 8;

    return 'gif'  if $test =~ /^GIF\d\d[a-z]/;
    return 'jpeg' if $test =~ /^\xFF\xD8\xFF/;
    return 'png'  if $test =~ /^\x89PNG\x0D\x0A\x1A\x0A/;
    return 'pnm'  if $test =~ /^\s*P[1-6]/;
    # potentially could handle TIFF, except that libtiff cannot accept
    # a filehandle as input for image_tiff(). GD images do not have files.
    return;
}
```
becomes
```
sub _detect_image_format {
    my $fh = shift();
    if (ref($fh) ne 'SCALAR') {
        $fh->seek(0, 0);
        binmode $fh, ':raw';
    }

    my ($test, $bytes_read);
    if (ref($fh) eq 'SCALAR') {
        $test = substr($$fh, 0, 8);
        $bytes_read = length($test);
    } else {
        $bytes_read = $fh->read($test, 8);
        $fh->seek(0, 0);
    }
    return unless $bytes_read and $bytes_read == 8;

    return 'gif'  if $test =~ /^GIF\d\d[a-z]/;
    return 'jpeg' if $test =~ /^\xFF\xD8\xFF/;
    return 'png'  if $test =~ /^\x89PNG\x0D\x0A\x1A\x0A/;
    return 'pnm'  if $test =~ /^\s*P[1-6]/;
    # potentially could handle TIFF, except that libtiff cannot accept
    # a filehandle as input for image_tiff(). GD images do not have files.
    return;
}
```
and in PNG_IPL.pm new():
```
    binmode($fh, ':raw');
...
    close($fh);
```
change to
```
    if (ref($fh) ne 'SCALAR') {
        binmode($fh, ':raw');
    }
...
    if (ref($fh) ne 'SCALAR') {
        close($fh);
    }
```
because a SCALAR handle can't be binmode'd or closed (it gives errors).

Do you think this is the right approach, or would you do it differently? With these latest changes, my tests work in 5.26, 5.32, and 5.38; and nice.pl works in 5.38. PDF::API2 still fails, as its code needs updating.

**Comment by sciurius** [comment]
The test program tests all variants, PDF::API2 supports variants 1 - 3, but not the last one (scalar ref). The failure you see is to be expected until PDF::API2 fixes this.

I strongly suggest to use positive tests in all cases. E.g.

````
if (ref($fh) eq 'GLOB') { ... FILE, IO::Handle ... }
elsif (ref($fh) eq 'GD::Image') { ... }
elsif (ref($fh) eq 'SCALAR') { ... }
elsif (ref($fh) eq 'IO::String') { ...}
else { die }
````
In particular, the final `else die` is important to signal hard to find user errors. 

In the cases of GD::Image, IO::File and IO::String you may want to test for isa to allow derived classes. E.g.
````
my $fh = IO::File->new;
warn ref($fh), "\n";           # prints IO::File
warn $fh->isa('IO::Handle');   # prints 1 so you can do IO::Handle operations.
````

Take care to use `UNIVERSAL::isa` for the tests.
````
if ( ref($fh) eq 'GLOB'
     || UNIVERSAL::isa($fh,'IO::Handle') ) { ... FILE, IO::Handle ... }
elsif ( UNIVERSAL::isa($fh,'GD::Image') ) { ... }
elsif ( ref($fh) eq 'SCALAR' ) { ... }
elsif ( UNIVERSAL::isa($fh,'IO::String') ) { ...}
else { die }
````

**Comment by PhilterPaper** [comment]
Wow, that's a lot to mull over. It sounds, though, like you're basically happy with the revisions, and are just suggesting some tuning and improvements. I'm not sure which is the base class and what it derived from what, and when it is safe to do an `isa("base_class")` and when I need to address various classes specifically. If you have experience with these particular issues, I'd be happy to get some guidance from you (needless to say, I really haven't worked with some of these). Also, when it is important to use `UNIVERSAL::isa(` versus `->isa(`? Are there random "isa" routines floating around?

I will get this into PDF::Builder in GitHub in the very near future. As for PDF::API2, if you want your applications to keep running on it, you'll have to deal with Steve (I'm banned from that repository). If you want a timely update, you'll probably have to do a PR for it, and hope he accepts it.

**Comment by sciurius** [comment]
Basically, by examining the isa, you ask a thing 'can you do this' instead of 'are you'. E.g.
````
use IO::Scalar;
$fd = IO::Scalar->new;
say ref($fd);                    # IO::Scalar
say $fd->isa('IO::Handle');      # 1
````
So the ref is not `IO::Handle`, but the object can be used as an `IO::Handle`.

You can call `isa` only on a blessed reference (i.e., an instance of a class). OTOH, `UNIVERSAL::isa(...)` can be used on anything. This includes `UNIVERSAL::isa($fh,'GLOB')` and `UNIVERSAL::isa($fh,'SCALAR')`.

As for PDF::API2, one of these days I'll submit a proposal to either shoehorn all forms of input types in a single variable (multiple dispatch), or add an alternative function (e.g., `image_from_scalar`). In most situations the calling program knows that it has the contents in a scalar so why not benefit from this knowledge. Also, as I learned long ago, it may be good practice to distinguish functions that do I/O from functions that do not.

**Comment by PhilterPaper** [comment]
In your example, then, `IO::Handle` is the _base_ class (parent) to `IO::Scalar`, and Scalar is _derived_ from Handle? My understanding is that `IO::Scalar` can do anything `IO::Handle` can do (although some functionality may have been overridden and thus be different). In the reverse case, `IO::Handle` can do some of what `IO::Scalar` can do, but not everything. While (in theory) you could treat an `IO::Scalar` as an `IO::Handle`, you could not necessarily do the reverse.

What I'm guessing that you're trying to do is, if you know that Scalar is derived from Handle, and for certain functions the object can be treated as either Scalar or Handle, it is safe to "isa" for the parent class (and perhaps do other things)? I'm just wondering if that's really a safe thing to do, and if it wouldn't be better to use a little more code to make it clear that an object is one or the other, that might even diverge in functionality some time in the future. That is, to test for `isa(Handle) || isa(Scalar)` might be clearer to a maintainer (and more future-proof) than to test just `isa(Handle)`?

Finally, if `UNIVERSAL::isa($thing, kind)` is more, uh, _universal_ in application than `$thing->isa(kind)`, it sounds like it might be a good idea to use it.

**Comment by PhilterPaper** [comment]
I'll close this now, unless you want to reopen it for more discussion.
