### ISSUE TITLE
Additional image support

### ISSUE THREAD

**Issue by PhilterPaper** [sciurius/perl-SVGPDF#3]
I played with raster-images-within-SVG a bit to see if anything worked beyond inlined PNG. The results are promising, after a minor fix to SVGPDF's Image.pm:

* PNG with inline data: works (this is the original go.svg sample)
* PNG referring to an external file works
* JPG/JPEG with inline data works
* JPG/JPEG referring to an external file works
* GIF with inline data does NOT work (image/gif not supported in Image.pm)
* GIF referring to an external file now works
* TIF/TIFF with inline data does NOT work (image/tiff not supported; libtiff does not accept filehandles). Possibly with "nouseGT" set, the libtiff issue goes away?
* TIF/TIFF referring to an external file now works
* PBM (PNM, PPM, PGM) with inline data does NOT work (image/pXm not supported)
* PBM referring to an external file now works. presumably the other PxM will also work.

The fix needed in SVGPDF's Image.pm is change
```
    elsif ( $link =~ m!^.+\.(png|jpe?g)$! && -s $link ) {
```
to
```
    elsif ( $link =~ m!^.+\.(png|jpe?g|gif|tiff?|p[bgpn]m)$!i && -s $link ) {
```
Note that mixed/uppercase file extensions are now permitted (necessary for Windows support). The SVG spec only requires that PNG and JPEG (and SVG?) be supported, but if other types can be supported at low cost, that would be a plus. Please consider doing so.

I don't know what else needs to be done in the first part of Image.pm, where it tries to handle `image/png` and `image/jpeg` inline data, besides expanding the list to tiff/tif, gif, pXm (I'm not sure what mime types cover PNM, PBM, PGM, PPM). For TIFF, I need to do something to allow filehandles to be passed to libtiff via Graphics::TIFF. That may be the same problem we encountered trying to pass Perl filehandles to an XS routine (Image::PNG::Libpng). Worst case I can probably read the filehandle into a temporary file on the Perl side, send that the usual way, and erase the file. That should probably be handled in `image_tiff()` rather than SVGPDF, but I need to think about it some more.

GD is the only remaining image type to consider... that's not something that an SVG file could contain, is it? The spec mentions allowing SVG _images_, but I'm not sure if that is the same thing you ran into with MJdisplay.svg.

**Comment by sciurius** [comment]
I've pushed "Add gif, tif(f) and pnm to recognized image extensions.", with regtest.
Since TIFF and PxM are not auto-sensed, I supply the `format` option in these cases.

Note that there may be test failures flagged as TODO. I'm using a ref scalar to pass inline data. Also, I do not supply the `nouseIPL` option assuming that crash will be fixed as well.

Note that `12_image3.svg` tests all file types but somehow the TIFF files do not come out correctly with PDF::API2.

**Comment by PhilterPaper** [comment]
Great! When 0.084 hits CPAN, I'll be sure to throw my tests against it. I will also implement the use of a filehandle with Graphics::TIFF (libtiff) soon (in PDF::Builder), so you should be able to do the TIFF-embedded-in-SVG test when making use of Graphics::TIFF. Unfortunately, unless you can think of a better way, it's probably going to be to create a temporary file to pass in as a filepath, although I _will_ look at the Graphics::TIFF code to see if something similar can be done as SVGPDF does with Image::PNG::Libpng, and pass on a PR to @carygravel.

Will let you know the results here. If you're not planning a CPAN update soon, please let me know so I can manually update from GitHub (I was having trouble with CPAN update on 5.32).

**Comment by PhilterPaper** [comment]
Note to readers: see ssimms/pdfapi2/issues/72 for JV's proposal for an `image_from_scalar()`. I may wait to see if there's action on this front, as I would want to implement this is PDF::Builder, too.

**Comment by sciurius** [comment]
Installing from CPAN:
* download kit
* unpack kit
* cd into unpack folder
* perl Makefile.PL
* gmake all test
* gmake install

Install from git:
* git clone https://github.com/sciurius/perl-SVGPDF
* cd perl-SVGPDF
* perl Makefile.PL
* gmake all test
* gmake install

Shouldn't make a difference.

**Comment by PhilterPaper** [comment]
Yes, I had to get a copy from GitHub for 5.32 update, and install it that way. 5.26 and 5.38 went smoothly with just the normal `cpan` upgrade process. I'm kind of wondering if I did something odd during the initial (pre-CPAN distribution) installation on 5.32, that's messing up further upgrades. I went so far as to uninstall on 5.32, but there may be something residual that's messing it up. We'll see at the next CPAN upgrade, unless that's a long way off.

**Comment by PhilterPaper** [comment]
Per discussions in #4, I would _prefer_ to have the next release of PDF::Builder (3.027) fully support SVGs with embedded (inlilne) images, but if you want to wait for API2 to support `image_from_scalar()`, I can go ahead with file-only support (already working). When a later SVGPDF drops, with embedded image support, it will suddenly and miraculously start working in Builder! Or, if it is expected to be some time, I can think about a work-around (read filehandle, write a temporary file, and replace the filehandle by that file path string).

It will be _at least_ 3 or 4 months (say, mid to late Spring) before the next Builder release, so no great rush.

**Comment by PhilterPaper** [comment]
Hi Johan,

I came across a rather familiar looking squirrel in https://www.youtube.com/watch?v=NdBSYUbaAZg at time 7:45. Enjoy!

**Comment by PhilterPaper** [comment]
I'll close this now, unless you want to reopen it for further discussion.
