### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by PhilterPaper** [sciurius/perl-SVGPDF#4]
Per your report that PDF::Builder did not run some t-tests correctly, I tried to d/l from GitHub and do a build. Makefile.PL reports the following files missing: 
```
t/regtest/12_image3.ref
t/regtest/12_image3.svg
t/regtest/squirrel.ppm
```
Once these are on GitHub, I will try to build and test SVGPDF. I added the two 900 tests to my batch script, as xt/ t-tests don't get run automatically (at least with CPAN).

You're probably deep into New Years Eve celebrations by this time, so have a good one and see you next year!

**Comment by sciurius** [comment]
I've added the files. Sorry for the inconvenience.

Best wishes for 2024!

**Comment by PhilterPaper** [comment]
Thanks for the quick fix. I installed SVGPDF the normal way (Makefile.PL, gmake, gmake test, gmake install) and no problems were reported for either API2 or Builder. I can run 901_regtest.t standalone, too, and it says it is using PDF::Builder and both tests are successful. What errors do you encounter?

By the way, what is the difference between t/90x_regtest.t and xt/90x_regtest.t? They both seem to run the same t/900_regtest.pl.

**Comment by sciurius** [comment]
This is what I get:
````
ok 1 - use PDF::Builder;
ok 2 - use SVGPDF;
ok 3 - Have SVGPDF object
# Testing 35 SVG files with PDF::Builder
ok 4 - Have XO results
ok 5 - regtest/01_basic1.svg
...
ok 64 - Have XO results
ok 65 - regtest/11_svg1.svg
ok 66 - Have XO results
ok 67 - regtest/12_image1.svg
All 67 subtests passed 

Test Summary Report
-------------------
t/901_regtest.t (Wstat: 139 (Signal: SEGV, dumped core) Tests: 67 Failed: 0)
  Non-zero wait status: 139
  Parse errors: No plan found in TAP output
Files=1, Tests=67,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.33 cusr  0.03 csys =  0.39 CPU)
Result: FAIL
````
The tests all pass, and then perl crashes when exiting. Memory corruption due to one of the libraries?

> t/90x_regtest.t and xt/90x_regtest.t? They both seem to run the same t/900_regtest.pl.

That is correct, but they use a different set of test files. The t/regtest/* tests should succeed, the xt/regtest/* tests may contain failures. The xt tests should not be in the CPAN kit (I'll remove them).

**Comment by PhilterPaper** [comment]
Ah, mine was only running the first two because I had no `t/.testall` file! You might want to include that?

Once I created .testall, here's the results:
```
C:\Users\Phil\Desktop\jv-SVGPDF>perl t\901_regtest.t
ok 1 - use PDF::Builder;
ok 2 - use SVGPDF;
ok 3 - Have SVGPDF object
# Testing 35 SVG files with PDF::Builder
ok 4 - Have XO results
ok 5 - regtest/01_basic1.svg
ok 6 - Have XO results
ok 7 - regtest/01_basic2.svg
ok 8 - Have XO results
ok 9 - regtest/02_rectangle1.svg
ok 10 - Have XO results
ok 11 - regtest/02_rectangle2.svg
ok 12 - Have XO results
ok 13 - regtest/03_circle1.svg
ok 14 - Have XO results
ok 15 - regtest/04_ellipse1.svg
ok 16 - Have XO results
ok 17 - regtest/05_line1.svg
ok 18 - Have XO results
ok 19 - regtest/05_line1cap.svg
ok 20 - Have XO results
ok 21 - regtest/05_line1dash.svg
ok 22 - Have XO results
ok 23 - regtest/05_line1join.svg
ok 24 - Have XO results
ok 25 - regtest/06_polyline1.svg
ok 26 - Have XO results
ok 27 - regtest/07_polygon1.svg
ok 28 - Have XO results
ok 29 - regtest/08_path1a1.svg
ok 30 - Have XO results
ok 31 - regtest/08_path1a2.svg
ok 32 - Have XO results
ok 33 - regtest/08_path1a3.svg
ok 34 - Have XO results
ok 35 - regtest/08_path1a4.svg
ok 36 - Have XO results
ok 37 - regtest/08_path1a5.svg
ok 38 - Have XO results
ok 39 - regtest/08_path1a6.svg
ok 40 - Have XO results
ok 41 - regtest/08_path1a7.svg
ok 42 - Have XO results
ok 43 - regtest/08_path1c1.svg
ok 44 - Have XO results
ok 45 - regtest/08_path1q1.svg
ok 46 - Have XO results
ok 47 - regtest/08_path1q2.svg
ok 48 - Have XO results
ok 49 - regtest/08_path1s1.svg
ok 50 - Have XO results
ok 51 - regtest/08_path1t1.svg
ok 52 - Have XO results
ok 53 - regtest/08_path2.svg
ok 54 - Have XO results
ok 55 - regtest/09_text1.svg
ok 56 - Have XO results
ok 57 - regtest/09_tspan1.svg
ok 58 - Have XO results
ok 59 - regtest/10_transform1.svg
ok 60 - Have XO results
ok 61 - regtest/10_transform2.svg
ok 62 - Have XO results
ok 63 - regtest/10_transform3.svg
ok 64 - Have XO results
ok 65 - regtest/11_svg1.svg
ok 66 - Have XO results
ok 67 - regtest/12_image1.svg
not ok 68 - Have XO results # TODO Not yet implemented
#   Failed (TODO) test 'Have XO results'
#   at ./900_regtest.pl line 65.
# Files regtest/12_image2.out and regtest/12_image2.ref differ at line 8
#   <  ***missing***1
#   >    xo save
not ok 69 - regtest/12_image2.svg # TODO Not yet implemented
#   Failed (TODO) test 'regtest/12_image2.svg'
#   at ./900_regtest.pl line 71.
ok 70 - Have XO results
ok 71 - regtest/12_image3.svg
ok 72 - Have XO results
ok 73 - regtest/13_units1.svg
ok 74 - Tested 35 files
ok 75 - Verdana|normal|normal font handler callbacks
ok 76 - sans|normal|bold font handler callbacks
ok 77 - sans|normal|normal font handler callbacks
ok 78 - sans-serif|normal|normal font handler callbacks
ok 79 - serif|normal|normal font handler callbacks
1..79

C:\Users\Phil\Desktop\jv-SVGPDF>       
```                                              
I'm not sure what you're expecting for 68 and 69.

**Comment by sciurius** [comment]
> Ah, mine was only running the first two because I had no t/.testall file! You might want to include that?

Better still, I've removed the `.testall` tweak.

> I'm not sure what you're expecting for 68 and 69.

Please pull.
With this version I have full OK results for PDF::API2, and `Signal: SEGV, dumped core` for the PDF::Builder regtests.
It could be something with my system (I recently upgraded to the newest Fedora version).
I'll try Windows and MacOS tomorrow.

**Comment by PhilterPaper** [comment]
900 is OK
901 (rest of it is OK):
```
ok 67 - regtest/12_image1.svg
not ok 68 - Have XO results
#   Failed test 'Have XO results'
#   at ./900_regtest.pl line 61.
# Files regtest/12_image2.out and regtest/12_image2.ref differ at line 8
#   <  ***missing***1
#   >    xo save
not ok 69 - regtest/12_image2.svg
#   Failed test 'regtest/12_image2.svg'
#   at ./900_regtest.pl line 64.
ok 70 - Have XO results
```

**Comment by PhilterPaper** [comment]
Yes, both go.svg and 12_image2.svg have embedded (inline) PNG images and are probably failing in the same way. I know that go.svg was working OK until the last few days -- did you change something? I haven't had time to go back through the tickets and see what was changed. Was it using IO::String before, which you don't want to go back to?

> We really should have a distinct `image_from_scalar` method. Hope that Steve reacts soon.

Don't hold your breath waiting for action. He tends to go six months or more between touching PDF::API2, and then churns out a whole bunch of updates at once. I seem to recall that you offered to do a PR for this -- I'll be happy to fit it into PDF::Builder (should be almost identical) should you go ahead and do it for API2.

As to my schedule for needing a fully working SVGPDF to support new SVG-related functionality in PDF::Builder, that's at least 3 or 4 months off. Most of it (non-embedded images aside) is already there. If you want to wait until API2 moves, that's your call. I would prefer to release the next Builder with full support, but it wouldn't be the end of the world if my first release failed to support inline (embedded) images -- my code could be there, waiting for the updated SVGPDF to drop, or I could have a temporary work-around (read the image into a temp file and use that, which is already supported).

**Comment by sciurius** [comment]
I see two options at this stage.

First option is to disable IPL for embedded (PNG) images in SVGPDF. This makes all tests (in particular 12_image2) succeed.

Second option is to revert to IO::Scalar again, but then you will have to check for that and work around it to be able to use IPL.

I will augment the inline image handling to support the other formats.

**Comment by sciurius** [comment]
I've pushed the first option. 

Also, all recognized types should now be able to be embbedded (untested).

**Comment by PhilterPaper** [comment]
Great! With your latest code, I can now run all your t-tests and examples without error, _and_ I can run all my SVG with raster image samples! I had to modify TIFF (when using Graphics::TIFF) to write out an open filehandle (GLOB) to a temporary file and use that. Unfortunately, it won't erase the temporary file after, so they will build up. Maybe you can try it on Linux at some point and see if the file is erased? Might the filehandle be something other than a GLOB? That's the only non-real-file thing I test for, and is what your code is supplying to me. I haven't looked to see what other kinds of filehandles (if any) that other image routines handle (everything is pure Perl except for TIFF with GT and PNG with IPL).

Did you say you were going to get rid of the xt/ tests? I see they're gone from MANIFEST but are still brought over (at least a non-CPAN installation, direct from GitHub). Are they expected to disappear from the CPAN build?

Regarding `nouseIPL`, _eventually_ I would like to see IPL use enabled, so that more advanced PNG files can be used. These are fairly esoteric features, so it's not a show-stopper. If it's a matter of writing out a temporary file, you could consider doing what I did in TIFF with GT, or maybe there's a better way. Come to think of it, I should test PNG with IPL using a normal Perl filehandle as its input -- I would think it would have the same issues as TIFF with GT.

Let me know if you want my collection of SVG-with-raster-image files for testing, if you don't have your own. I will put my latest changes to Builder into GitHub after I send this off, so you can try it on your system at some point.

**Comment by sciurius** [comment]
According to the SVG specs, the formats PNG, JPG and SVG **must** be supported.
It should not matter if the source is external (disk, network) or embedded.

Firefox and Chrome support JPG, PNG, SVG and GIF. RSVG also supports TIFF. SVGPDF does not support SVG as an image type. 

So I would suggest to not bother about TIFF, X?M and P?G, even if PDF::Builder can handle these. You will never encounter one of these in real life SVG files. I'd like to remove these from SVGPDF unless you have compelling reasons not to do so.

> Did you say you were going to get rid of the xt/ tests?

These tests are mostly for development purposes, so I keep them in the repo but they are not included in the CPAN kit.

> Unfortunately, it won't erase the temporary file after, so they will build up

`open(my $tmp, "+>", undef)` will give a non-persisting temp file but it may suffer from the same problems as `open(my $tmp, '<', \$scalar)`. For everything else, File::Temp is your friend.

**Comment by sciurius** [comment]
With the latest commits, the following image types are handled correctly, both disk based and inline data: PNG, JPG, GIF, TIFF, PBM, PGM, PPM. Probably XBM and XPM as well, didn't test.

For TIFF I write the inline data to a temp file and pass the file **name** to `pdf->image`; for the other types it is the opened file **handle**. Currently the best way to have the tests pass with API2 and Builder.

**Comment by PhilterPaper** [comment]
Um, Houston, we have a problem...
```
C:\Users\Phil\Desktop\jv-SVGPDF>gmake test
Skip blib\lib\SVGPDF\Circle.pm (unchanged)
Skip blib\lib\SVGPDF\Parser.pm (unchanged)
Skip blib\lib\SVGPDF\Tspan.pm (unchanged)
Skip blib\lib\SVGPDF\CSS.pm (unchanged)
Skip blib\lib\SVGPDF\Defs.pm (unchanged)
Skip blib\lib\SVGPDF\Contrib\Bogen.pm (unchanged)
Skip blib\lib\SVGPDF\Svg.pm (unchanged)
Skip blib\lib\SVGPDF\Polygon.pm (unchanged)
Skip blib\lib\SVGPDF\Rect.pm (unchanged)
Skip blib\lib\SVGPDF\Polyline.pm (unchanged)
Skip blib\lib\SVGPDF\Image.pm (unchanged)
Skip blib\lib\SVGPDF\Line.pm (unchanged)
Skip blib\lib\SVGPDF\Element.pm (unchanged)
Skip blib\lib\SVGPDF.pm (unchanged)
Skip blib\lib\SVGPDF\G.pm (unchanged)
Skip blib\lib\SVGPDF\Use.pm (unchanged)
Skip blib\lib\SVGPDF\Style.pm (unchanged)
Skip blib\lib\SVGPDF\Path.pm (unchanged)
Skip blib\lib\SVGPDF\Contrib\PathExtract.pm (unchanged)
Skip blib\lib\SVGPDF\Text.pm (unchanged)
Skip blib\lib\SVGPDF\PAST.pm (unchanged)
Skip blib\lib\SVGPDF\Ellipse.pm (unchanged)
Skip blib\lib\SVGPDF\FontManager.pm (unchanged)
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/001_load.t ..... 1/19 # Testing SVGPDF 0.083, Perl 5.032001, C:\Strawberry\perl\bin\perl.exe
# Using PDF::API2 version 2.043
t/001_load.t ..... ok
t/002_load.t ..... ok
t/100_css.t ...... ok
t/101_css.t ...... ok
t/102_css.t ...... ok
t/103_css.t ...... ok
t/104_css.t ...... ok
t/201_xml.t ...... ok
t/202_xml.t ...... ok
t/203_xml.t ...... ok
t/900_regtest.t .. 1/? # Testing 36 SVG files with PDF::API2
# Files regtest/12_image3.out and regtest/12_image3.ref differ at line 48
#   <  SVG: Unhandled or missing image link: "regtest/squirrel.gif"
#   >    xo save

#   Failed test 'regtest/12_image3.svg'
#   at ./900_regtest.pl line 64.
t/900_regtest.t .. 72/? # Looks like you failed 1 test of 81.
t/900_regtest.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/81 subtests
t/901_regtest.t .. 1/? # Testing 36 SVG files with PDF::Builder
t/901_regtest.t .. 66/? # Files regtest/12_image3.out and regtest/12_image3.ref differ at line 48
#   <  SVG: Unhandled or missing image link: "regtest/squirrel.gif"
#   >    xo save

#   Failed test 'regtest/12_image3.svg'
#   at ./900_regtest.pl line 64.
# Looks like you failed 1 test of 81.
t/901_regtest.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/81 subtests

Test Summary Report
-------------------
t/900_regtest.t (Wstat: 256 (exited 1) Tests: 81 Failed: 1)
  Failed test:  71
  Non-zero exit status: 1
t/901_regtest.t (Wstat: 256 (exited 1) Tests: 81 Failed: 1)
  Failed test:  71
  Non-zero exit status: 1
Files=12, Tests=231,  8 wallclock secs ( 0.06 usr +  0.09 sys =  0.16 CPU)
Result: FAIL
Failed 2/12 test programs. 2/231 subtests failed.
gmake: *** [Makefile:897: test_dynamic] Error 1

C:\Users\Phil\Desktop\jv-SVGPDF>
```

**Comment by PhilterPaper** [comment]
> With the latest commits, the following image types are handled correctly, both disk based and inline data: PNG, JPG, GIF, TIFF, PBM, PGM, PPM. Probably XBM and XPM as well, didn't test.

Sounds great (once it installs cleanly). If they'll handle X?M too, I'll have to look into that some day (explicit support for X?M in PDF::Builder). Is there much use of these formats? I've never played with them.

> For TIFF I write the inline data to a temp file and pass the file name to pdf->image; for the other types it is the opened file handle. Currently the best way to have the tests pass with API2 and Builder.

Yesterday, I put in changes to PDF::Builder's handling of filehandles to TIFF (using GT). It too uses a temp file (I presume you saw this, as you commented on my issues with erasing the temp file). Anyway, this shouldn't interfere with your TIFF filehandle work and vice-versa.

Once I get a clean install, I'll test against my samples. I also still need to test TIFF+GT with a filehandle input.

**Comment by sciurius** [comment]
Just pull :)

**Comment by sciurius** [comment]
> Is there much use of these formats?

As I mentioned earlier, you'll hardly ever encounter X?M files in real life applications, and most certainly not in SVG files.

**Comment by PhilterPaper** [comment]
> Just pull :)

Pull your finger? Oh! D/L the latest. My mistake!

Looking good. Your install, t-tests, and examples work fine. And my samples script runs cleanly. Everything seems fine at this point.

**Comment by sciurius** [comment]
Good to hear.

I'm moving the data-url handling to File::LoadLines. For SVGPDF this means that **everywhere** you need data, it can now be a file name on disk, on the network, or inlined. 

Programmatically it means calling `loadblob` and you have the data, no matter where it came from.

**Comment by PhilterPaper** [comment]
Sounding good. The issue remaining is whether you're making full use of PNG+IPL and TIFF+GT when you feed them an embedded image via a filehandle. If you're using "nouseIPL" and "nouseGT", you're losing some PNG and a lot of TIFF functionality. I have already added a kludge to TIFF+GT to read the filehandle into a temp file, usable outside of SVGPDF (but I'm not happy with it, and it sounds like you may have duplicated that in your code). In PNG+IPL, I'm not sure in PDF::API2 that it actually tries to read a PNG file from a filehandle or still reads it in with Perl and only uses IPL code to do a fast unpack. It's possible that PNG+IPL will need to (like TIFF) read a filehandle into a temp file. I need to play with `image_png()` in PDF::Builder and see how it behaves with a filehandle input, and similar for `image_tiff()`. Maybe @carygravel and @benkasminbullock can chime in with their thoughts (here or on #3)?

**Comment by sciurius** [comment]
To paraphrase a famous phone maker: you're holding it wrong.

Every image processing subroutine (and/or library) wants the data in memory to operate upon. As a service they provide a means to start with a file name, since these resources often reside in disk files.

Well, times have changed and the resources are now presented in memory (as a scalar) ready to be operated upon. The only thing required is a small refactoring of the routines from (simplified):
````
sub image( $filename ) {
    my $data;
    ... open $filename, read file into $data ...
    .... analyse, process, ...
}
````
to
````
sub image( $filename ) {
    my $data;
    ... open $filename, read file into $data ...
    image_from_scalar( $data );
}
sub image_from_scalar( $data ) {
    .... analyse, process, ...
}
````
Image::PNG::LibPNG already works that way.

**Comment by PhilterPaper** [comment]
For consistent and orthogonal image interfaces, I have gone ahead and given each (except GD) the ability to accept either a filepath/name or filehandle (GLOB, at a minimum). SVGPDF still works. TIFF+GT writes out a temporary file.

I'm not sure if you use it, but IPL has a `read_from_scalar` call that might be useful. It doesn't appear that GT has such a call -- maybe we could ask Jeff to add it, assuming that libtiff either has such a call or can be persuaded to accept a data string.

**Comment by sciurius** [comment]
> I have gone ahead and given each (except GD) the ability

Great!

> I'm not sure if you use it, but IPL has a read_from_scalar call that might be useful

Definitely. But I'm not using IPL explicitly, PDF::Builder does.

**Comment by PhilterPaper** [comment]
Is there any point to modifying PDF::Builder to use `read_from_scalar()`? If your code is working now (except possibly some lost functionality due to use of `nouseIPL`), you still would want to keep your code compatible with PDF::API2. Once API2 uses read_from_scalar, I will be happy to consider putting such code into Builder. Keep in mind that Builder uses IPL much differently than API2 does, so it may not be a simple switch.

**Comment by PhilterPaper** [comment]
Just to let you know that CPAN's 0.084 appears to install and test cleanly on Windows 10, Perl 5.26/5.32/5.38 via the CPAN installer.

You might want to check your copyright dates on README.md, LICENSE.md, and lib/SVGPDF.pm and change latest year 2023 to 2024. I see you also have some warnings in README.md and possibly elsewhere about this being a work in progress and probably not useful yet -- I take it you're not ready yet to remove those warnings.

**Comment by sciurius** [comment]
FYI: http://www.cpantesters.org/cpan/report/36b81801-707f-1014-837e-0c9b5913ae8e

**Comment by sciurius** [comment]
> I see you also have some warnings in README.md and possibly elsewhere about this being a work in progress and probably not useful yet -- I take it you're not ready yet to remove those warnings.

It will be a WIP until it is integrated and operational in PDF::Builder. I expect (but hope not) this may require a few potentially breaking API changes...

About its usefulness... Well, if it works it is useful. It is useful for the cases we tested. But often when I try an arbitrary SVG from the net it requires a few, sometimes minor, changes/enhancements. And some don't work at all.

**Comment by PhilterPaper** [comment]
Interesting. So far, only my 5.38 shows 0.084 available on CPAN (within a day or two I should see it available on 5.26 and 5.32). I just uninstalled and reinstalled 0.084 (official CPAN release) on 5.38.0 and it claims to have installed cleanly. Running the t-tests and examples also worked. I forced an install (`cpan .` in the unpacked 0.084 package) on 5.26 and 5.32 and they reported clean, too. The error appears to be something involving loading Image::PNG::Libpng -- perhaps the testers used IPL 0.57_01 rather than 0.57? It looks like the same problem for other testers.

Here's the code in question:
```
    my ($rc);
    $rc = eval {
        require Image::PNG::Libpng;
        1;
    };
    if (!defined $rc) { $rc = 0; }  # else is 1  <=== line 4512
    if ($rc) {                                   <=== or possibly this one?
	# installed, but not up to date?
	if ($Image::PNG::Libpng::VERSION < $LpngVersion) { $rc = 0; }
    }
```
I thought `eval` should return a True or False (1 or 0 or undef?), but possibly it's returning the version number for some reason? Something like `0.57` should work fine, but `0.57_01` I could see causing problems in a numeric comparison. What should I be testing `$rc` for here? I'm not absolutely sure which is line 4512 in Builder.pm, as I don't know what version of Builder they're using. Would better code be
```
    if (defined $rc) {
        $rc = 1;
    } else {
        $rc = 0;
    }
```
I can pop out a new PDF::Builder release very soon if you think that will fix the problem.

> But often when I try an arbitrary SVG from the net it requires a few, sometimes minor, changes/enhancements. And some don't work at all.

Well, SVG is huge and complex. There's no way that your code will ever cover 100% of it, and to attempt to do so would mean that it will _never_ be released. The best you can do is to cover a reasonable portion of it (that will be useful for your purposes, as well as PDF::Builder's). If something shows up later that breaks it, you make a decision whether it's worth extending to cover that case, and maybe issue a new release. That's about the best you can do.

**Comment by sciurius** [comment]
I'm pretty sure it is

    $Image::PNG::Libpng::VERSION < $LpngVersion

The message reads "Argument "0.57_01" isn't numeric in numeric lt (<)".

**Comment by PhilterPaper** [comment]
Yeah, that would probably be better.

According to the `eval` documentation, it returns the last value found, so for some reason IPL chose to have the $VERSION somewhere rather than the customary 1.
```
    my ($rc);
    $rc = eval {
        require Image::PNG::Libpng $LpngVersion;
        1;
    };
    # make sure rc is a 0 or 1 and not a version number or something else odd
    if (defined $rc) { 
        $rc = 1;
    } else {
        $rc = 0;
    }
```
I take it this will work for "odd" development versions? And the version given is the _minimum_ (not the _only_) acceptable version? `$LpngVersion` itself should always be something like `0.57`. 

Same thing for Graphics::TIFF and any other place where a similar `eval` is done.

The current code has been there for years; apparently this time is the first time that a "development" version was put on CPAN for IPL or GT, and tripped up this code!

**Comment by sciurius** [comment]
$rc = eval {
        require Image::PNG::Libpng $LpngVersion;
        1;
    };

This guarantees that `$rc` is either undefined, or `1`.

    # make sure rc is a 0 or 1 and not a version number or something else odd
    if (defined $rc) { 
        $rc = 1;
    } else {
        $rc = 0;
    }

This is superfluous now, but in case you're paranoid this can be written as `!!$rc||0`.

**Comment by PhilterPaper** [comment]
```
 $rc = eval {
    require Image::PNG::Libpng $LpngVersion;
    1;
};
```
> This guarantees that `$rc` is either undefined, or `1`.

You would think so, but the error reported shows that `$rc` was "0.57_01" (without the `$LpngVersion`). Does specifying a minimum version _absolutely guarantee_ `undef` or `1`, regardless of what IPL's last value was? I looked at the docs for `require` and they don't say much about this. If not, I'm going to be super paranoid about this and use the if-then-else code. Your one-liner would probably be OK, but I think my version is more fool-proof. I don't have a development version of IPL to test against to be sure.

Since this is mucking up the CPANTS testing for SVGPDF, would you like me to push out PDF::Builder 3.027 as soon as possible? I'm in the middle of fixing something with `column()`, so it may take a few days. You might take the opportunity to update your t-tests to round all floating point numbers to some reasonable number of digits, so they'll compare the same on all systems (look at PDF::Table's t/PDF-Table.t for an example). The other errors reported (mismatched output) I have no idea about.

**Comment by sciurius** [comment]
> ou would think so, but the error reported shows that $rc was "0.57_01"

As I pointed out, the diagnostic is not on the comparison to $rc (that is 1 or undef), but at line 4515 where Image::PNG::Library VERSION is compared.

> let me know if I should push out 3.027 early to CPAN

No sweat. If testers are on the bleeding edge they will upgrade to IPL 0.58 and the problem will disappear soon.

> I think it's a very bad idea to use "development" or "test" versions of libraries in testing.

Yes. OTOH the idea behind smoke testing is to test on as many combinations of systems and tools. Sometimes you just need to ignore failures that are beyond the scope of your own software.

**Comment by PhilterPaper** [comment]
OK, clean install/test/examples for SVGPDF 0.085 on Windows 10, Perl 5.26/5.32/5.38. The only nit is in SVGPDF.pm you have the first and last year separated by a period (.) instead of a comma (,).

**Comment by PhilterPaper** [comment]
I tried this out:
```
my$rc = eval {
    require Image::PNG::Libpng $LpngVersion;
    1;
};
```
and it fails with "Scalar found where operator expected at...".
```
    require Image::PNG::Libpng 0.57;
``` 
fails with "Number found where operator expected at...".
```
    require "Image::PNG::Libpng $LpngVersion";
``` 
fails by claiming that the module is _not_ installed (returns $rc undef), though no error messages.
```
    require "Image::PNG::Libpng 0.57";
``` 
fails the same way.
```
my$rc = eval "
    require Image::PNG::Libpng $LpngVersion;
    1;
";
```
and it fails with "Scalar found where operator expected at...". Ditto for hard-coded version number.

```
my$rc = eval {
    use Image::PNG::Libpng $LpngVersion;
    1;
};
```
and it fails with "'' is not exported by the Image::PNG::Libpng module...".
```
    use Image::PNG::Libpng 0.57;
``` 
_seems_ to work, but I'd rather have a variable list consolidated at the top of the file. I'm also not sure how 'use' is going to behave compared to 'require'. If I remove Graphics::TIFF, I get a major error (not caught by 'eval') that Graphics::TIFF cannot be found.
```
    use "Image::PNG::Libpng 0.60";
``` 
fails with a major error (not caught be 'eval') that "Image::PNG::Libpng 0.60 required".

I'm not sure what to use here. If I _don't_ have a version number, the first example works fine. The problem is that any returned $VERSION might have a funny format (e.g., 0.57_01), which breaks numeric comparisons. Have you actually required a specific minimum level of another package in any of your code?

**Comment by sciurius** [comment]
`perldoc -f use` gives you all the answers.
