### ISSUE TITLE
Testing on both API2 and Builder

### ISSUE THREAD

**Issue by PhilterPaper** [sciurius/perl-SVGPDF#5]
I see from your t/90x*.t tests that you appear to test on one of PDF::API2 _or_ PDF::Builder, depending on your preference "use this" environment variable and which is/are installed. Would it be better to test on _both_ systems rather than just one (assuming both are installed)? I was thinking of the following scheme:
`t/nn_someTest_a.t` set up to run on PDF::API2 (SKIP if not installed)
`t/nn_someTest_b.t` set up to run on PDF::Builder (SKIP if not installed)
You appear to prefer leading a test name with a number (presumably to better control the order), so you would probably want to use \_a or \_b suffix. It would be possible to use a\_ or b\_ _prefix_, too.

Both would test if the requested PDF was installed, and if it is, invoke `perl [-T] ./common/nn_someTest.pl A` (or `B`) which carries most of the test code. This way, both API2 and Builder would be tested during install (if available), rather than just a "preferred" one. The common code would expect 'A' or 'B' as the first (or only) argument* and would do the usual "use PDF::xxxxx;" and "$pdf = PDF::xxxxx->new" etc. depending on which one was requested. The common code would not have to test whether the requested library exists, but if manually invoked from the command line, there could be an error if that library is not installed. To test _again_ within the common test would be safer. Or, you can test only within the common code, and make the two stubs even lighter.

\* `our $api;` could also be used to pass this information.

t-tests which don't use a PDF library could be suffixed with "_x" or none at all.

If you want control over which PDF library you use, you could just directly invoke `perl [-T] t/nn_someTest_X.t` where X is a or b, rather than using an environment variable.

If a test (or example) requires the -T flag, that could be supplied in the stub, and you don't have to remember to add it to the command line. The downside is that you now have three files instead of one, per test or example, but two of them are very light stubs that merely call the common .pl script with the appropriate command line parameter(s), and are almost the same in each case.

I'm thinking of changing PDF::Table and Text::KnuthPlass over to such a setup, but wanted to check with you whether you had already tried this route, and it failed to work well.

Examples, which are now hard-coded as PDF::API2, could use a similar system:
`examples/a/some_example.pl`  set up for API2
`examples/b/some_example.pl`  set up for Builder
etc., with anything not requiring PDF::***** either in the root `examples/` or in `examples/x/`. Again, there could be a common core for each example, with only a check on whether the requested library is available. I plan to add an example to PDF::Table showing off "column" formatting within a table (Builder only), so the 'A' stub would just be a dummy to skip it with "This capability is not implemented in PDF::API2".

`tools/2_t-tests.pl` and `tools/3_examples.pl` would by default run all tests/examples under both API2 and Builder, but could have a flag to do just one or the other.

**Comment by sciurius** [comment]
I don't follow.
There are two kinds of tests, the ones with `9` prefix and the others. The other tests test SVGPDF aspects that are independent of PDF backend.

The `900_regtest.t` and `901_regtest.t` tests a series of svg files on `PDF::API2` (`900_regtest.t`) and `PDF__Builder` (`901_regtest.t`) using common code `900_regtest.pl`. If both PDF backends are installed, both are tested with the same set of test files.

**Comment by PhilterPaper** [comment]
You're doing then what I was thinking of doing for my two packages. Perhaps I should have phrased it better -- "Does this design work well for you?" Also, I think your examples are hard coded to PDF::API2 -- maybe they can use a similar mechanism (file, env variable, or command-line flag)? 

Environment variables are a PITA in Windows, so I would like to work around that. In PDF::Table I used a "preferences" file to specify one or the other, when both were installed. I'll have to think of a good way to do it. I do like the use of `$api` so I can define it once and reuse it anywhere I need the package name. I thought I had tried that once a long time ago -- maybe I made a mistake.

**Comment by PhilterPaper** [comment]
It sounds like I will end up (for PDF::Table and Text::KnuthPlass) doubling all the t-tests that make use of PDF::* (API2 or Builder) and making a PDF::API2-specific version (skipped if PDF::API2 not installed) and a PDF::Builder-specific version (skipped if PDF::Builder not installed). Most t-tests will not be run if neither PDF::* is installed, and all will be run if both are installed. There might be an environment variable switch to disable one or the other. I was hoping to avoid having two slightly different copies of each t-test, but it looks like the way to go. Neither PDF::* library is a hard prereq, so it is possible that neither will be found.

Regarding examples/, each will need to support both PDF::* libraries, but run with only one at a time, if both are available. If only one library is available, obviously the examples must run with that one. If neither is available, all will quit early (those using PDF -- some Text::KnuthPlass examples are ASCII text file output). If both are available, look for a command line switch to specify which, falling back to an environment variable, and then to the preferred library (PDF::Builder).
