### ISSUE TITLE
vbox versus bbox, 'combine' option, vwidth versus width

### ISSUE THREAD

**Issue by PhilterPaper** [sciurius/perl-SVGPDF#7]
Since SVGPDF hasn't changed in over two months, I'm hoping it's safe to actually start on final code for PDF::Builder 3.027 using SVGPDF.

The POD for SVGPDF suggests the use of anonymous array `$_->{'vbox'}` for the bounding box, but I see that the array returned by `$xo->bbox()` is still available. `bbox()` is the one I've been using, but since it (no longer?) seems to be documented, I'm wondering if you are still planning to support (and document) it. The two arrays are slightly different in content. I just don't want to get caught using `bbox()` if you are planning to withdraw it. What are your plans? So long as the baseline y is available in `vbox`, I could change to that if necessary.

Also, I don't have any multiple `<svg>` examples to test the 'combine' option with. Am I reading the POD correctly that 'stacked' returns them as a vertical stack of _separately_ rendered images (non-overlapped), while 'bbox' combines them into a single overlapped result with the same coordinate system? I presume that _not_ giving **combine** will simply yield an array of separate image objects, and rendering one after another (vertically) would more or less be the same as `combine=>'stacked'`?

Finally, what is the distinction between `width` and `vwidth` (ditto for height)? I see that they are often different, but am not sure exactly what they are giving (or their relation to the bbox).

**Comment by sciurius** [comment]
SVGPDF is sufficiently stable to be used, even though not everything is fully implemented.

`bbox`  is same as the `vbox`, but using bottom-left and top-right coordinates. I've added it to the docs.

> not giving combine will simply yield an array of separate image objects, and rendering one after another (vertically) would more or less be the same as combine=>'stacked'?

Correct. Maybe the attached image clarifies it a bit.
![svg_combine](https://github.com/sciurius/perl-SVGPDF/assets/1118804/b8be9463-e99e-433d-a63a-f6ae689c7860)

Note that combine bbox is not implemented yet.

The distinction between `vwidth` and `width` (and (v)height) is in the docs. For example, a typical MathJax formula has `width` of 5000 (internal coordinates) and `vwidth` of 11ex (user coordinates).

**Comment by PhilterPaper** [comment]
OK, thanks for confirming my understanding. I look forward to the updated GitHub and CPAN. It sounds like I can safely continue to use the `bbox()` method. I need to get a better understanding of width/vwidth so I can tell _my_ users about it.

I will give users the option of using `combine=>'bbox'`, in hopes that you will have that implemented in the near future. I don't anticipate any of my uses of SVG to need combining, but it is possible that someone may have an externally-produced SVG that includes multiple `<svg>`s that they want combined in an intuitive manner (i.e., overlapping with the same coordinate system). 

Regarding `combine=>'bbox'`, will that still work with different scalings (not just different origin locations)? Will you need to rescale at least one `<svg>`? I'm not sure if SVG requires the same scaling in all `<svg>`s, or if they can vary.

If you plan to include such illustrations with your documentation, you may want to show `combine=>'stacked'` with a `sep` gap between them, to remind users that's possible.

**Comment by sciurius** [comment]
> I will give users the option of using combine=>'bbox', in hopes that you will have that implemented in the near future.

I currently have no plans to implement this. Maybe when I find an interesting use case for it.

> you may want to show combine=>'stacked' with a sep gap between them,

Good suggestion, thanks.

**Comment by PhilterPaper** [comment]
PDF::Builder SVG support released (PhilterPaper/Perl-PDF-Builder/issues/89).
