### ISSUE TITLE
version conflict

### ISSUE THREAD

**Issue by PhilterPaper** [sciurius/perl-SVGPDF#9]
I see you just released 0.088.1. However, I noticed that the "Module version" given in CPAN is 0.88.1. It appears that META.json 'provides' has a typo. That might cause a conflict somewhere. I haven't checked elsewhere to see if the version number is consistent.

**Comment by sciurius** [comment]
Thanks for letting me know. Apparently the META generators do not respect the quotes around my version.
If all goes well 0.088 < v0.88.1 < 0.089 ...

**Comment by PhilterPaper** [comment]
Have you looked at X.XXX_1 instead? That may be more conventional and supported by the META generators.

**Comment by sciurius** [comment]
An underscore is conventionally used to denote a development (beta, non-stable) version. Some tools (and people) skip versions with underscore by default, so I think that would be no option in this case.

**Comment by PhilterPaper** [comment]
Hmm. If you don't want to use underscore, and your tools don't handle V.M.m numbers correctly, it sounds like you'll have to roll your own tools (such as a build script -- e.g., see PDF::Builder's devtools/PDFbuild.pl) to distribute the desired version format throughout the built package. Or something; up to you.

**Comment by sciurius** [comment]
For good understanding: Nothing is wrong with these version numbers. There is no typo in META. You don't have to worry that "[t]hat might cause a conflict somewhere".
